---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sokodigital-uploads
  labels:
    app: sokodigital
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
